training:
  num_workers: 0
  train_iters: 100_000 # Total number of optimizer steps (provided by pipelinerl)
  # wandb: # Enable this block if we want to log to Weights & Biases
  #   project_name: ${job.project_name}
  #   group_name: ${job.project_version}
  logs:
    interval: 1 # Logging frequency in optimizer steps (one training iteration)
  checkpoint: # How often to save checkpoints in native fast-llm format
    interval: 1000
  export: # How often to export checkpoints in HF format
    interval: 1000
    format: qwen2 # Export format (should match the format of the checkpoint used to start training)

batch:
  micro_batch_size: 1 # For RL, all rollouts are packed into a single sample
  sequence_length: 8192 # Max rollout length accepted; also the training sample length
  batch_size: 16 # Number of samples per optimizer step
  truncate_documents: False # We do not want truncation for RL rollouts
  #use_preference_spans: true
  use_loss_masking_spans: true
  use_grpo_data: True

data:
  sampling:
    shuffle: disabled # Streaming dataset ignores shuffling
  datasets:
    training:
      type: streaming # Type of dataset: Redis-backed streaming dataset
      host: localhost # Redis server host. Must be provided by pipelinerl
      port: 11000 # Redis server port. Must be provided by pipelinerl

pretrained:
  format: qwen2 # Base model format (provided by pipelinerl)
  path: /home/toolkit/Qwen2.5-0.5B-Instruct # Base model checkpoint path (provided by pipelinerl)
  model_weights: yes # Indicates that we load pretrained weights and start training from the base model

model:
  base_model:
    head:
      losses:
          grpo:
            type: grpo
            epsilon_low: 0.2
            epsilon_high: 0.2
  multi_stage:
    zero_stage: 2 # Note: choosing appropriate Zero, TP, PP, or SP settings is important
                  # for fitting larger models and optimizing speed/memory; this is usually
                  # tuned per training setup
  distributed:
    compute_dtype: bf16
    tensor_parallel: 1 # TP=2 used to test broadcasting; not needed for a small model
    pipeline_parallel: 1
    sequence_data_parallel: 1

run:
  experiment_dir: "/home/toolkit/test/denis/Qwen2.5-0.5B-Instruct" # Provided by pipelinerl


callbacks:
  streaming:
    type: streaming
    host: localhost  # overridden by launch.py via CLI: callbacks.streaming.host=...
    port: 11000      # overridden by launch.py via CLI: callbacks.streaming.port=...
    broadcast:
      backend: nccl
      external_world_size: 1  # overridden by launch.py
      host: localhost          # overridden by launch.py
      port: 26901              # overridden by launch.py
    export:
      format: qwen2
      model_weights: true
      optimizer_state: false
