wrong_answer_not_finished: -1.0
no_answer_not_finished: -1.0
correct_answer_not_finished: -1.0
no_answer_finished: -1.0
wrong_answer_finished: -0.5
correct_answer_finished: 1.0
unparsable_not_finished: -1.0
unparsable_finished: -1.0